MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/media/aditya/A69AFABA9AFA85D9/Cruzr/code/fb_mask_rcnn/maskrcnn-benchmark/fat_trained_models/model_final_90k.pth"
  # WEIGHT: "/media/aditya/A69AFABA9AFA85D9/Cruzr/code/fb_mask_rcnn/maskrcnn-benchmark/model_final.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictorWithPose"
    NUM_CLASSES: 22
    NUM_VIEWPOINTS: 1000
    NUM_INPLANE_ROTATIONS: 68
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  POSE_ON: True
DATASETS:
  TRAIN: ("fat_pose_2018_train_cocostyle",)
  TEST: ("fat_pose_2018_val_cocostyle",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 0
SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (30000,)
  # MAX_ITER: 17500
  MAX_ITER: 50000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
#SOLVER:
#  BASE_LR: 0.001
#  WEIGHT_DECAY: 0.00001
#  STEPS: (2000,)
#  MAX_ITER: 32000
#  IMS_PER_BATCH: 1
